// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: CardServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated CardServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCardServiceClient is a mock of CardServiceClient interface.
type MockCardServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCardServiceClientMockRecorder
	isgomock struct{}
}

// MockCardServiceClientMockRecorder is the mock recorder for MockCardServiceClient.
type MockCardServiceClientMockRecorder struct {
	mock *MockCardServiceClient
}

// NewMockCardServiceClient creates a new mock instance.
func NewMockCardServiceClient(ctrl *gomock.Controller) *MockCardServiceClient {
	mock := &MockCardServiceClient{ctrl: ctrl}
	mock.recorder = &MockCardServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardServiceClient) EXPECT() *MockCardServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCardServiceClient) Add(ctx context.Context, in *protos.AddCardRequest, opts ...grpc.CallOption) (*protos.CardModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.CardModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockCardServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCardServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockCardServiceClient) AddBulk(ctx context.Context, in *protos.AddCardBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockCardServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockCardServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockCardServiceClient) Delete(ctx context.Context, in *protos.DeleteCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCardServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCardServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockCardServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteCardBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockCardServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockCardServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockCardServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllCardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCardServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCardServiceClient)(nil).GetAll), varargs...)
}

// GetByAccount mocks base method.
func (m *MockCardServiceClient) GetByAccount(ctx context.Context, in *protos.GetCardsByAccountRequest, opts ...grpc.CallOption) (*protos.GetAllCardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByAccount", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccount indicates an expected call of GetByAccount.
func (mr *MockCardServiceClientMockRecorder) GetByAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccount", reflect.TypeOf((*MockCardServiceClient)(nil).GetByAccount), varargs...)
}

// GetById mocks base method.
func (m *MockCardServiceClient) GetById(ctx context.Context, in *protos.GetCardByIdRequest, opts ...grpc.CallOption) (*protos.CardModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.CardModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCardServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCardServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockCardServiceClient) GetByIds(ctx context.Context, in *protos.GetCardByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllCardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockCardServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockCardServiceClient)(nil).GetByIds), varargs...)
}

// Update mocks base method.
func (m *MockCardServiceClient) Update(ctx context.Context, in *protos.UpdateCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCardServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCardServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockCardServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateCardBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockCardServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockCardServiceClient)(nil).UpdateBulk), varargs...)
}
