// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: AtmServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated AtmServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockAtmServiceClient is a mock of AtmServiceClient interface.
type MockAtmServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAtmServiceClientMockRecorder
	isgomock struct{}
}

// MockAtmServiceClientMockRecorder is the mock recorder for MockAtmServiceClient.
type MockAtmServiceClientMockRecorder struct {
	mock *MockAtmServiceClient
}

// NewMockAtmServiceClient creates a new mock instance.
func NewMockAtmServiceClient(ctrl *gomock.Controller) *MockAtmServiceClient {
	mock := &MockAtmServiceClient{ctrl: ctrl}
	mock.recorder = &MockAtmServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAtmServiceClient) EXPECT() *MockAtmServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAtmServiceClient) Add(ctx context.Context, in *protos.AddAtmRequest, opts ...grpc.CallOption) (*protos.AtmModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.AtmModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockAtmServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAtmServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockAtmServiceClient) AddBulk(ctx context.Context, in *protos.AddAtmBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockAtmServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockAtmServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockAtmServiceClient) Delete(ctx context.Context, in *protos.DeleteAtmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAtmServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAtmServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockAtmServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteAtmBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockAtmServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockAtmServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockAtmServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllAtmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAtmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAtmServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAtmServiceClient)(nil).GetAll), varargs...)
}

// GetByBranch mocks base method.
func (m *MockAtmServiceClient) GetByBranch(ctx context.Context, in *protos.GetAtmsByBranchRequest, opts ...grpc.CallOption) (*protos.GetAllAtmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByBranch", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAtmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBranch indicates an expected call of GetByBranch.
func (mr *MockAtmServiceClientMockRecorder) GetByBranch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBranch", reflect.TypeOf((*MockAtmServiceClient)(nil).GetByBranch), varargs...)
}

// GetById mocks base method.
func (m *MockAtmServiceClient) GetById(ctx context.Context, in *protos.GetAtmByIdRequest, opts ...grpc.CallOption) (*protos.AtmModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.AtmModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAtmServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAtmServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockAtmServiceClient) GetByIds(ctx context.Context, in *protos.GetAtmByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllAtmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAtmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockAtmServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockAtmServiceClient)(nil).GetByIds), varargs...)
}

// GetByLocationSubStr mocks base method.
func (m *MockAtmServiceClient) GetByLocationSubStr(ctx context.Context, in *protos.GetAtmsByLocationSubStrRequest, opts ...grpc.CallOption) (*protos.GetAllAtmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByLocationSubStr", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAtmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLocationSubStr indicates an expected call of GetByLocationSubStr.
func (mr *MockAtmServiceClientMockRecorder) GetByLocationSubStr(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLocationSubStr", reflect.TypeOf((*MockAtmServiceClient)(nil).GetByLocationSubStr), varargs...)
}

// GetByStatus mocks base method.
func (m *MockAtmServiceClient) GetByStatus(ctx context.Context, in *protos.GetAtmsByStatusRequest, opts ...grpc.CallOption) (*protos.GetAllAtmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByStatus", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAtmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockAtmServiceClientMockRecorder) GetByStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockAtmServiceClient)(nil).GetByStatus), varargs...)
}

// Update mocks base method.
func (m *MockAtmServiceClient) Update(ctx context.Context, in *protos.UpdateAtmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAtmServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAtmServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockAtmServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateAtmBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockAtmServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockAtmServiceClient)(nil).UpdateBulk), varargs...)
}
