// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: ExchangeRateServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated ExchangeRateServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockExchangeRateServiceClient is a mock of ExchangeRateServiceClient interface.
type MockExchangeRateServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeRateServiceClientMockRecorder
	isgomock struct{}
}

// MockExchangeRateServiceClientMockRecorder is the mock recorder for MockExchangeRateServiceClient.
type MockExchangeRateServiceClientMockRecorder struct {
	mock *MockExchangeRateServiceClient
}

// NewMockExchangeRateServiceClient creates a new mock instance.
func NewMockExchangeRateServiceClient(ctrl *gomock.Controller) *MockExchangeRateServiceClient {
	mock := &MockExchangeRateServiceClient{ctrl: ctrl}
	mock.recorder = &MockExchangeRateServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeRateServiceClient) EXPECT() *MockExchangeRateServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockExchangeRateServiceClient) Add(ctx context.Context, in *protos.AddExchangeRateRequest, opts ...grpc.CallOption) (*protos.ExchangeRateModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.ExchangeRateModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockExchangeRateServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockExchangeRateServiceClient) AddBulk(ctx context.Context, in *protos.AddExchangeRateBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockExchangeRateServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockExchangeRateServiceClient) Delete(ctx context.Context, in *protos.DeleteExchangeRateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExchangeRateServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockExchangeRateServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteExchangeRateBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockExchangeRateServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockExchangeRateServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExchangeRateServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).GetAll), varargs...)
}

// GetByBaseCurrency mocks base method.
func (m *MockExchangeRateServiceClient) GetByBaseCurrency(ctx context.Context, in *protos.GetExchangeRateByBaseCurrencyRequest, opts ...grpc.CallOption) (*protos.GetAllExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByBaseCurrency", varargs...)
	ret0, _ := ret[0].(*protos.GetAllExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBaseCurrency indicates an expected call of GetByBaseCurrency.
func (mr *MockExchangeRateServiceClientMockRecorder) GetByBaseCurrency(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBaseCurrency", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).GetByBaseCurrency), varargs...)
}

// GetById mocks base method.
func (m *MockExchangeRateServiceClient) GetById(ctx context.Context, in *protos.GetExchangeRateByIdRequest, opts ...grpc.CallOption) (*protos.ExchangeRateModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.ExchangeRateModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockExchangeRateServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockExchangeRateServiceClient) GetByIds(ctx context.Context, in *protos.GetExchangeRateByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockExchangeRateServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).GetByIds), varargs...)
}

// GetCount mocks base method.
func (m *MockExchangeRateServiceClient) GetCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*protos.CountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCount", varargs...)
	ret0, _ := ret[0].(*protos.CountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockExchangeRateServiceClientMockRecorder) GetCount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).GetCount), varargs...)
}

// Update mocks base method.
func (m *MockExchangeRateServiceClient) Update(ctx context.Context, in *protos.UpdateExchangeRateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExchangeRateServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockExchangeRateServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateExchangeRateBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockExchangeRateServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockExchangeRateServiceClient)(nil).UpdateBulk), varargs...)
}
