// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: LoanPaymentServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated LoanPaymentServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockLoanPaymentServiceClient is a mock of LoanPaymentServiceClient interface.
type MockLoanPaymentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockLoanPaymentServiceClientMockRecorder
	isgomock struct{}
}

// MockLoanPaymentServiceClientMockRecorder is the mock recorder for MockLoanPaymentServiceClient.
type MockLoanPaymentServiceClientMockRecorder struct {
	mock *MockLoanPaymentServiceClient
}

// NewMockLoanPaymentServiceClient creates a new mock instance.
func NewMockLoanPaymentServiceClient(ctrl *gomock.Controller) *MockLoanPaymentServiceClient {
	mock := &MockLoanPaymentServiceClient{ctrl: ctrl}
	mock.recorder = &MockLoanPaymentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanPaymentServiceClient) EXPECT() *MockLoanPaymentServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockLoanPaymentServiceClient) Add(ctx context.Context, in *protos.AddLoanPaymentRequest, opts ...grpc.CallOption) (*protos.LoanPaymentModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.LoanPaymentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockLoanPaymentServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockLoanPaymentServiceClient) AddBulk(ctx context.Context, in *protos.AddLoanPaymentBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockLoanPaymentServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockLoanPaymentServiceClient) Delete(ctx context.Context, in *protos.DeleteLoanPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockLoanPaymentServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockLoanPaymentServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteLoanPaymentBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockLoanPaymentServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockLoanPaymentServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllLoanPaymentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllLoanPaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLoanPaymentServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockLoanPaymentServiceClient) GetById(ctx context.Context, in *protos.GetLoanPaymentByIdRequest, opts ...grpc.CallOption) (*protos.LoanPaymentModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.LoanPaymentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockLoanPaymentServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockLoanPaymentServiceClient) GetByIds(ctx context.Context, in *protos.GetLoanPaymentByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllLoanPaymentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllLoanPaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockLoanPaymentServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).GetByIds), varargs...)
}

// GetByLoan mocks base method.
func (m *MockLoanPaymentServiceClient) GetByLoan(ctx context.Context, in *protos.GetLoanPaymentsByLoanRequest, opts ...grpc.CallOption) (*protos.GetAllLoanPaymentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByLoan", varargs...)
	ret0, _ := ret[0].(*protos.GetAllLoanPaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLoan indicates an expected call of GetByLoan.
func (mr *MockLoanPaymentServiceClientMockRecorder) GetByLoan(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLoan", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).GetByLoan), varargs...)
}

// Update mocks base method.
func (m *MockLoanPaymentServiceClient) Update(ctx context.Context, in *protos.UpdateLoanPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLoanPaymentServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockLoanPaymentServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateLoanPaymentBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockLoanPaymentServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockLoanPaymentServiceClient)(nil).UpdateBulk), varargs...)
}
