// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: LoanServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated LoanServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockLoanServiceClient is a mock of LoanServiceClient interface.
type MockLoanServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockLoanServiceClientMockRecorder
	isgomock struct{}
}

// MockLoanServiceClientMockRecorder is the mock recorder for MockLoanServiceClient.
type MockLoanServiceClientMockRecorder struct {
	mock *MockLoanServiceClient
}

// NewMockLoanServiceClient creates a new mock instance.
func NewMockLoanServiceClient(ctrl *gomock.Controller) *MockLoanServiceClient {
	mock := &MockLoanServiceClient{ctrl: ctrl}
	mock.recorder = &MockLoanServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanServiceClient) EXPECT() *MockLoanServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockLoanServiceClient) Add(ctx context.Context, in *protos.AddLoanRequest, opts ...grpc.CallOption) (*protos.LoanModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.LoanModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockLoanServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockLoanServiceClient)(nil).Add), varargs...)
}

// Delete mocks base method.
func (m *MockLoanServiceClient) Delete(ctx context.Context, in *protos.DeleteLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockLoanServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoanServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockLoanServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteLoanBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockLoanServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockLoanServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockLoanServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllLoansResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllLoansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLoanServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLoanServiceClient)(nil).GetAll), varargs...)
}

// GetByCustomer mocks base method.
func (m *MockLoanServiceClient) GetByCustomer(ctx context.Context, in *protos.GetLoansByCustomerRequest, opts ...grpc.CallOption) (*protos.GetAllLoansResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByCustomer", varargs...)
	ret0, _ := ret[0].(*protos.GetAllLoansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCustomer indicates an expected call of GetByCustomer.
func (mr *MockLoanServiceClientMockRecorder) GetByCustomer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCustomer", reflect.TypeOf((*MockLoanServiceClient)(nil).GetByCustomer), varargs...)
}

// GetById mocks base method.
func (m *MockLoanServiceClient) GetById(ctx context.Context, in *protos.GetLoanByIdRequest, opts ...grpc.CallOption) (*protos.LoanModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.LoanModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockLoanServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockLoanServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockLoanServiceClient) GetByIds(ctx context.Context, in *protos.GetLoanByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllLoansResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllLoansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockLoanServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockLoanServiceClient)(nil).GetByIds), varargs...)
}

// GetCount mocks base method.
func (m *MockLoanServiceClient) GetCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*protos.CountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCount", varargs...)
	ret0, _ := ret[0].(*protos.CountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockLoanServiceClientMockRecorder) GetCount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockLoanServiceClient)(nil).GetCount), varargs...)
}

// Update mocks base method.
func (m *MockLoanServiceClient) Update(ctx context.Context, in *protos.UpdateLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLoanServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanServiceClient)(nil).Update), varargs...)
}
