// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: CustomerServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated CustomerServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCustomerServiceClient is a mock of CustomerServiceClient interface.
type MockCustomerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerServiceClientMockRecorder
	isgomock struct{}
}

// MockCustomerServiceClientMockRecorder is the mock recorder for MockCustomerServiceClient.
type MockCustomerServiceClientMockRecorder struct {
	mock *MockCustomerServiceClient
}

// NewMockCustomerServiceClient creates a new mock instance.
func NewMockCustomerServiceClient(ctrl *gomock.Controller) *MockCustomerServiceClient {
	mock := &MockCustomerServiceClient{ctrl: ctrl}
	mock.recorder = &MockCustomerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerServiceClient) EXPECT() *MockCustomerServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCustomerServiceClient) Add(ctx context.Context, in *protos.AddCustomerRequest, opts ...grpc.CallOption) (*protos.CustomerModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.CustomerModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockCustomerServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCustomerServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockCustomerServiceClient) AddBulk(ctx context.Context, in *protos.AddCustomerBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockCustomerServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockCustomerServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockCustomerServiceClient) Delete(ctx context.Context, in *protos.DeleteCustomerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockCustomerServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteCustomerBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockCustomerServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockCustomerServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockCustomerServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllCustomersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCustomersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCustomerServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCustomerServiceClient)(nil).GetAll), varargs...)
}

// GetByDateRange mocks base method.
func (m *MockCustomerServiceClient) GetByDateRange(ctx context.Context, in *protos.GetByDateRangeRequest, opts ...grpc.CallOption) (*protos.GetAllCustomersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByDateRange", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCustomersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateRange indicates an expected call of GetByDateRange.
func (mr *MockCustomerServiceClientMockRecorder) GetByDateRange(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateRange", reflect.TypeOf((*MockCustomerServiceClient)(nil).GetByDateRange), varargs...)
}

// GetById mocks base method.
func (m *MockCustomerServiceClient) GetById(ctx context.Context, in *protos.GetCustomerByIdRequest, opts ...grpc.CallOption) (*protos.CustomerModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.CustomerModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCustomerServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCustomerServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockCustomerServiceClient) GetByIds(ctx context.Context, in *protos.GetCustomerByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllCustomersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCustomersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockCustomerServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockCustomerServiceClient)(nil).GetByIds), varargs...)
}

// GetBySubstring mocks base method.
func (m *MockCustomerServiceClient) GetBySubstring(ctx context.Context, in *protos.GetBySubstringRequest, opts ...grpc.CallOption) (*protos.GetAllCustomersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBySubstring", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCustomersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubstring indicates an expected call of GetBySubstring.
func (mr *MockCustomerServiceClientMockRecorder) GetBySubstring(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubstring", reflect.TypeOf((*MockCustomerServiceClient)(nil).GetBySubstring), varargs...)
}

// Update mocks base method.
func (m *MockCustomerServiceClient) Update(ctx context.Context, in *protos.UpdateCustomerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockCustomerServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateCustomerBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockCustomerServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockCustomerServiceClient)(nil).UpdateBulk), varargs...)
}
