// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: AccountTypeServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated AccountTypeServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockAccountTypeServiceClient is a mock of AccountTypeServiceClient interface.
type MockAccountTypeServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTypeServiceClientMockRecorder
	isgomock struct{}
}

// MockAccountTypeServiceClientMockRecorder is the mock recorder for MockAccountTypeServiceClient.
type MockAccountTypeServiceClientMockRecorder struct {
	mock *MockAccountTypeServiceClient
}

// NewMockAccountTypeServiceClient creates a new mock instance.
func NewMockAccountTypeServiceClient(ctrl *gomock.Controller) *MockAccountTypeServiceClient {
	mock := &MockAccountTypeServiceClient{ctrl: ctrl}
	mock.recorder = &MockAccountTypeServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTypeServiceClient) EXPECT() *MockAccountTypeServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAccountTypeServiceClient) Add(ctx context.Context, in *protos.AddAccountTypeRequest, opts ...grpc.CallOption) (*protos.AccountTypeModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.AccountTypeModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockAccountTypeServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockAccountTypeServiceClient) AddBulk(ctx context.Context, in *protos.AddAccountTypeBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockAccountTypeServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockAccountTypeServiceClient) Delete(ctx context.Context, in *protos.DeleteAccountTypeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountTypeServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockAccountTypeServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteAccountTypeBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockAccountTypeServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockAccountTypeServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllAccountTypesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAccountTypesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAccountTypeServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockAccountTypeServiceClient) GetById(ctx context.Context, in *protos.GetAccountTypeByIdRequest, opts ...grpc.CallOption) (*protos.AccountTypeModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.AccountTypeModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAccountTypeServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockAccountTypeServiceClient) GetByIds(ctx context.Context, in *protos.GetAccountTypeByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllAccountTypesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllAccountTypesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockAccountTypeServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).GetByIds), varargs...)
}

// GetCount mocks base method.
func (m *MockAccountTypeServiceClient) GetCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*protos.CountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCount", varargs...)
	ret0, _ := ret[0].(*protos.CountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockAccountTypeServiceClientMockRecorder) GetCount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).GetCount), varargs...)
}

// Update mocks base method.
func (m *MockAccountTypeServiceClient) Update(ctx context.Context, in *protos.UpdateAccountTypeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountTypeServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockAccountTypeServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateAccountTypeBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockAccountTypeServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockAccountTypeServiceClient)(nil).UpdateBulk), varargs...)
}
