// Code generated by MockGen. DO NOT EDIT.
// Source: orch-go/api/generated (interfaces: CustomerAddressServiceClient)
//
// Generated by this command:
//
//	mockgen orch-go/api/generated CustomerAddressServiceClient
//

// Package mock_protos is a generated GoMock package.
package mock_protos

import (
	context "context"
	protos "orch-go/api/generated"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockCustomerAddressServiceClient is a mock of CustomerAddressServiceClient interface.
type MockCustomerAddressServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerAddressServiceClientMockRecorder
	isgomock struct{}
}

// MockCustomerAddressServiceClientMockRecorder is the mock recorder for MockCustomerAddressServiceClient.
type MockCustomerAddressServiceClientMockRecorder struct {
	mock *MockCustomerAddressServiceClient
}

// NewMockCustomerAddressServiceClient creates a new mock instance.
func NewMockCustomerAddressServiceClient(ctrl *gomock.Controller) *MockCustomerAddressServiceClient {
	mock := &MockCustomerAddressServiceClient{ctrl: ctrl}
	mock.recorder = &MockCustomerAddressServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerAddressServiceClient) EXPECT() *MockCustomerAddressServiceClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCustomerAddressServiceClient) Add(ctx context.Context, in *protos.AddCustomerAddressRequest, opts ...grpc.CallOption) (*protos.CustomerAddressModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*protos.CustomerAddressModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockCustomerAddressServiceClientMockRecorder) Add(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).Add), varargs...)
}

// AddBulk mocks base method.
func (m *MockCustomerAddressServiceClient) AddBulk(ctx context.Context, in *protos.AddCustomerAddressBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBulk indicates an expected call of AddBulk.
func (mr *MockCustomerAddressServiceClientMockRecorder) AddBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBulk", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).AddBulk), varargs...)
}

// Delete mocks base method.
func (m *MockCustomerAddressServiceClient) Delete(ctx context.Context, in *protos.DeleteCustomerAddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerAddressServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).Delete), varargs...)
}

// DeleteBulk mocks base method.
func (m *MockCustomerAddressServiceClient) DeleteBulk(ctx context.Context, in *protos.DeleteCustomerAddressBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockCustomerAddressServiceClientMockRecorder) DeleteBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).DeleteBulk), varargs...)
}

// GetAll mocks base method.
func (m *MockCustomerAddressServiceClient) GetAll(ctx context.Context, in *protos.GetAllRequest, opts ...grpc.CallOption) (*protos.GetAllCustomerAddressesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCustomerAddressesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCustomerAddressServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockCustomerAddressServiceClient) GetById(ctx context.Context, in *protos.GetCustomerAddressByIdRequest, opts ...grpc.CallOption) (*protos.CustomerAddressModel, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*protos.CustomerAddressModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCustomerAddressServiceClientMockRecorder) GetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).GetById), varargs...)
}

// GetByIds mocks base method.
func (m *MockCustomerAddressServiceClient) GetByIds(ctx context.Context, in *protos.GetCustomerAddressByIdsRequest, opts ...grpc.CallOption) (*protos.GetAllCustomerAddressesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIds", varargs...)
	ret0, _ := ret[0].(*protos.GetAllCustomerAddressesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockCustomerAddressServiceClientMockRecorder) GetByIds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).GetByIds), varargs...)
}

// Update mocks base method.
func (m *MockCustomerAddressServiceClient) Update(ctx context.Context, in *protos.UpdateCustomerAddressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerAddressServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).Update), varargs...)
}

// UpdateBulk mocks base method.
func (m *MockCustomerAddressServiceClient) UpdateBulk(ctx context.Context, in *protos.UpdateCustomerAddressBulkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBulk", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockCustomerAddressServiceClientMockRecorder) UpdateBulk(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockCustomerAddressServiceClient)(nil).UpdateBulk), varargs...)
}
