syntax = "proto3";

package protos;
option go_package = "orch-go/gen/protos;protos";
option csharp_namespace = "Core";

import "custom_types.proto";
import "google/protobuf/empty.proto";
import "customer_address.proto";

// Service performing analytical processing on customer addresses.
service CustomerAddressAnalyticService {
  // Analytical wrapper to retrieve all customer addresses.
  rpc ProcessGetAll (GetAllRequest) returns (GetAllCustomerAddressesResponse);
  // Analytical wrapper to retrieve a customer address by its unique ID.
  rpc ProcessGetById (GetCustomerAddressByIdRequest) returns (CustomerAddressModel);
  // Analytical wrapper to retrieve multiple customer addresses by their IDs.
  rpc ProcessGetByIds (GetCustomerAddressByIdsRequest) returns (GetAllCustomerAddressesResponse);
  // Analytical wrapper to retrieve the total count of customer addresses.
  rpc ProcessGetCount (google.protobuf.Empty) returns (CountResponse);
}
