syntax = "proto3";

package protos;
option go_package = "orch-go/gen/protos;protos";
option csharp_namespace = "Core";

import "google/protobuf/empty.proto";

// Service performing high-level general bank-wide analytics.
service GeneralAnalyticService {
    // Retrieves aggregated dashboard metrics across all services (counts, active totals, volumes).
    rpc GetGeneralCounts (google.protobuf.Empty) returns (GeneralCountsResponse);
}

// Response detailing general system-wide metrics and counts.
message GeneralCountsResponse {
    // The total count of registered customers.
    int32 total_customers = 1;
    // The total count of active bank accounts.
    int32 total_active_accounts = 2;
    // The total count of active cards.
    int32 total_active_cards = 3;
    // The total count of accounts with non-zero/active balances.
    int32 total_accounts_balance = 4;
    // The total count of active loans.
    int32 total_active_loans = 5;
    // The total count of active deposits.
    int32 total_active_deposits = 6;
    // The total number of transactions executed in the system.
    int32 total_transactions_count = 7;
    // The total aggregated amount of all transactions, represented as a string.
    string total_transactions_amount = 8;
}