syntax = "proto3";

package protos;
option go_package = "orch-go/gen/protos;protos";
option csharp_namespace = "Core";

import "custom_types.proto";
import "google/protobuf/empty.proto";
import "user_credential.proto";

// Service performing analytical processing on user credentials.
service UserCredentialAnalyticService {
  // Analytical wrapper to retrieve all user credentials.
  rpc ProcessGetAll (GetAllRequest) returns (GetAllUserCredentialsResponse);
  // Analytical wrapper to retrieve a user credential record by customer ID.
  rpc ProcessGetById (GetUserCredentialByIdRequest) returns (UserCredentialModel);
  // Analytical wrapper to retrieve multiple user credentials by their customer IDs.
  rpc ProcessGetByIds (GetUserCredentialByIdsRequest) returns (GetAllUserCredentialsResponse);
  // Analytical wrapper to retrieve user credentials by username.
  rpc ProcessGetByUsername (GetUserCredentialByUsernameRequest) returns (UserCredentialModel);
  // Analytical wrapper to retrieve the total count of user credentials.
  rpc ProcessGetCount (google.protobuf.Empty) returns (CountResponse);
}
